package ru.itlab.qa.tests;

// Generated by Selenium IDE

import lombok.SneakyThrows;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;


@SpringBootTest
public class QaCreateBoardTests extends TestBase {

    @After
    public void end(){
        tearDown();
    }

    @SneakyThrows
    @Test
    public void testCreatePost() {
        auth();
        createNewPost();
    }


}
